Link testing.
Using Firefox
0 PASS: linkhome ==> library for numerical computations in page
1 PASS: linkworkshop ==> IN in page
2 PASS: linkdoc ==> vectors and matrices in page
3 PASS: linklib ==> var numeric in page
4 PASS: linklibmin ==> var numeric= in page
Link testing complete. PASS: 5 FAIL: 0 Total: 5
Fetching http://numericjs.com/staging/documentation.html
In-browser unit tests.
Using Chrome
0 PASS: numeric.seedrandom.seedrandom('1'); Math.random = numeric.seedrandom.random; Math.random(); ==> 0.2694
1 PASS: A = [[1,2,3],[4,5,6]]; ==> [[1,2,3],[4,5,6]]
2 PASS: x = [7,8,9] ==> [7,8,9]
3 PASS: numeric.dot(A,x); ==> [50,122]
4 PASS: y = [10,1,2]; ==> [10,1,2]
5 PASS: numeric['+'](x,y) ==> [17,9,11]
6 PASS: numeric['>'](x,y) ==> [false,true,true]
7 PASS: numeric.add(x,y) ==> [17,9,11]
8 PASS: numeric.add([1,2],[3,4],[5,6],[7,8]) ==> [16,20]
9 PASS: A = [[1,2,3],[4,5,6],[7,1,9]] ==> [[1,2,3],[4,5,6],[7,1,9]]
10 PASS: Ainv = numeric.inv(A); ==> [[-0.9286,0.3571,0.07143],[-0.1429,0.2857,-0.1429],[0.7381,-0.3095,0.07143]]
11 PASS: numeric.precision = 10; x = 3.141592653589793 ==> 3.141592654
12 PASS: numeric.precision = 4; x ==> 3.142
13 PASS: numeric.identity(100) ==> ...LargeArray...
14 PASS: numeric.largeArray = 2; A = numeric.identity(4) ==> ...LargeArray...
FAIL: Chrome selenium tests. Details:
Traceback (most recent call last):
  File "selenium_tests.py", line 20, in test
    input.send_keys(tests[k][0]+'\n')
  File "/Library/Python/2.6/site-packages/selenium-2.24.0-py2.6.egg/selenium/webdriver/remote/webelement.py", line 156, in send_keys
    self._execute(Command.SEND_KEYS_TO_ELEMENT, {'value': typing})
  File "/Library/Python/2.6/site-packages/selenium-2.24.0-py2.6.egg/selenium/webdriver/remote/webelement.py", line 204, in _execute
    return self._parent.execute(command, params)
  File "/Library/Python/2.6/site-packages/selenium-2.24.0-py2.6.egg/selenium/webdriver/remote/webdriver.py", line 153, in execute
    response = self.command_executor.execute(driver_command, params)
  File "/Library/Python/2.6/site-packages/selenium-2.24.0-py2.6.egg/selenium/webdriver/remote/remote_connection.py", line 285, in execute
    return self._request(url, method=command_info[0], data=data)
  File "/Library/Python/2.6/site-packages/selenium-2.24.0-py2.6.egg/selenium/webdriver/remote/remote_connection.py", line 326, in _request
    response = opener.open(request)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 383, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 401, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 361, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 1141, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 1114, in do_open
    r = h.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 950, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 390, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 348, in _read_status
    line = self.fp.readline()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/socket.py", line 395, in readline
    data = recv(1)
KeyboardInterrupt
Traceback (most recent call last):
  File "selenium_tests.py", line 76, in <module>
    driver.quit()
  File "/Library/Python/2.6/site-packages/selenium-2.24.0-py2.6.egg/selenium/webdriver/chrome/webdriver.py", line 82, in quit
    self.service.stop()
  File "/Library/Python/2.6/site-packages/selenium-2.24.0-py2.6.egg/selenium/webdriver/chrome/service.py", line 83, in stop
    urllib2.urlopen("http://127.0.0.1:%d/shutdown" % self.port)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 124, in urlopen
    return _opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 383, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 401, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 361, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 1141, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib2.py", line 1116, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 61] Connection refused>
Fetching http://numericjs.com/staging/documentation.html
Traceback (most recent call last):
  File "selenium_tests.py", line 51, in <module>
    njs = urllib.urlopen(u0).read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib.py", line 87, in urlopen
    return opener.open(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib.py", line 203, in open
    return getattr(self, name)(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/urllib.py", line 338, in open_http
    h.endheaders()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 868, in endheaders
    self._send_output()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 740, in _send_output
    self.send(msg)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 699, in send
    self.connect()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/httplib.py", line 683, in connect
    self.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/socket.py", line 505, in create_connection
    sock.connect(sa)
  File "<string>", line 1, in connect
KeyboardInterrupt
